### ISSUE TITLE
Roster workcode svg class name change

### ISSUE THREAD

**Issue by timbellomo** [porcej/festis#1]
WFTS 7.1.16 changed the class name for workcode SVGs. 

Line 271 needs to be updated thusly:
`            rect = codes.find('svg', attrs={'class': 'svg'}).rect`

**Comment by porcej** [comment]
Issued resolved with commit [43eb92e
](https://github.com/porcej/festis/commit/43eb92e0806f410ae1a05ec3fc013d1e81117591)
